### ISSUE TITLE
Please make PyPI release for Django-5.0 support 

### ISSUE THREAD

**Issue by tumb1er** [dirkmoors/drf-tus#20]

**Comment by dirkmoors** [comment]
Thanks for the request. Unfortunately, I currently lack the time to rewrite the current setup.py to a new PyPi build system, and I currently cannot release the current "setup.py" format (it seems to be no longer supported). I you could provide a pull-request with a new package format (see: https://packaging.python.org/en/latest/key_projects/#hatch), I'd be happy to release a new version.

**Comment by tumb1er** [comment]
Thanks for response! One more packaging tool to rule them all :(  I'll try to dig deeper into it.

**Comment by BasemHamad** [comment]
@dirkmoors  can you look into the the PR ?

**Comment by dirkmoors** [comment]
@tumb1er While trying to release a new package version to Pypi, I noticed that the "setup.py" and "setup.cfg" are no longer present. According to https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#configuring-your-project I still need them though? Or how should I release to Pypi otherwise?

**Comment by tumb1er** [comment]
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packaging-your-project

You don't need setup files, you need `build` package to prepare .gz and .whl and `twine` to upload them to PyPI.

**Comment by dirkmoors** [comment]
https://pypi.org/project/drf-tus/ released!
